# Generated by Django 4.2.6 on 2023-12-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='location',
            field=models.CharField(blank=True, default='Kyrgyzstan', max_length=255, null=True),
        ),
    ]
