# Generated by Django 4.2.6 on 2023-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_car', models.CharField(max_length=255)),
                ('dollar_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('som_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Year_of_Manufacture', models.PositiveIntegerField()),
                ('Mileage', models.PositiveIntegerField()),
                ('Body_Type', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('Transmission', models.CharField(max_length=255)),
                ('Drive', models.CharField(max_length=255)),
                ('Steering', models.CharField(max_length=255)),
                ('Condition', models.CharField(max_length=255)),
                ('Customs', models.CharField(max_length=255)),
                ('Availability', models.CharField(max_length=255)),
                ('Region_City_of_Sale', models.CharField(max_length=255)),
                ('Registration', models.CharField(max_length=255)),
                ('Engine_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Engine_fuel_type', models.CharField(max_length=255)),
                ('Car_make', models.CharField(max_length=255)),
                ('Door_num', models.PositiveIntegerField()),
            ],
        ),
    ]
