# Generated by Django 4.2.6 on 2023-11-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='легковые', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_soms', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('engine', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('drive', models.CharField(max_length=20)),
                ('steering_left', models.BooleanField(default='слева')),
                ('condition', models.CharField(max_length=20)),
                ('customs_clearance', models.BooleanField(default=True)),
                ('exchange_offer', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
                ('region_city', models.CharField(default='Бишкек', max_length=100)),
                ('country', models.CharField(default='Кыргызстан', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_mvp.category')),
            ],
        ),
    ]
